// index typescript?
import { Shape } from "shex-methods";
import {
    chatShex,
    ChatShape,
    ChatShapeType,
    ChatShapeContext,
} from "node_modules\shex"; // generated by shex-codegen


const chat = new Shape<ChatShape>({
    id: "https://shaperepo.com/schemas/longChat#ChatShape",
    shape: chatShex,
    context: ChatShapeContext,
    type: ChatShapeType,
});

const newChat = await chat.create({
    doc: testDoc,
    data: {
        id: firstChatIri,
        type: ChatShapeType.LongChat,
        title: "Test Chat",
        author: webId,
        created: new Date(),
    } as ChatShape,
});
const { data, errors } = newChat;
